version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379