version: '3'
services:
  database:
    container_name: database
    image: postgres
    env_file: 
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database-export/:/opt/exports # To make this work, run chmod 777 ./database-exports
    ports:
      - 5432:5432
    restart: always
  redis:
    container_name: redis
    image: redis
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 32773:6379
    restart: always

volumes:
  database-data:
