name: SQLite CI

on: [push, pull_request]

jobs:
  build:
    name: Run Tests with SQLite
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install

      - name: Run Tests
        timeout-minutes: 5
        run: npm test
