name: SQLite CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Tests with SQLite
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - name: Run Tests
        timeout-minutes: 5
        run: npm test
