name: Codecov

on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
  codecov:
    name: Run Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
