name: Docker image builds
on:
  push:
    branches:
      - master
    paths:
      - containers/backup-db/**
  workflow_dispatch:

jobs:
  backup-db:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "db-backup"
      username: "ajayyy"
      folder: "./containers/backup-db"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}