name: Linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: Run Tests
        timeout-minutes: 5
        run: npm run lint