name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        env:
          PG_USER: ci_db_user
          PG_PASS: ci_db_pass
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Check running containers
        run: docker ps
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Run test suite
        env:
          TEST_POSTGRES: true
        run: npm test