name: sb-runner
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "sb-container"
      username: "ajayyy"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}