name: Docker image builds
on:
  push:
    branches:
      - debug
  workflow_dispatch:

jobs:
  sb-server:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "sb-server-debug"
      username: "ajayyy"
      folder: "."
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}